set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')

" Plugins go here
Plug 'itchyny/lightline.vim'
Plug 'bling/vim-bufferline'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree'
Plug 'lifepillar/vim-solarized8'

" All of your Plugins must be added before the following line
call plug#end()

set backspace=indent,eol,start
set mouse=a
set laststatus=2
set nobackup
set t_Co=256
set number relativenumber

syntax enable

set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized8_dark_flat

let g:lightline = {
  \     'colorscheme': 'giba',
  \     'active': {
  \         'left': [['mode', 'paste' ], ['readonly', 'filename', 'modified']],
  \         'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding']]
  \     }
  \ }

