set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')

" Plugins go here
Plug 'itchyny/lightline.vim'
Plug 'bling/vim-bufferline'
Plug '/usr/bin/fzf'
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
Plug 'lifepillar/vim-solarized8'
Plug 'terryma/vim-multiple-cursors'
Plug 'airblade/vim-gitgutter'

" All of your Plugins must be added before the following line
call plug#end()

set backspace=indent,eol,start
set mouse=a
set laststatus=2
set nobackup
set t_Co=256
set number relativenumber

syntax enable

set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized8_dark_flat

let g:lightline = {
  \     'colorscheme': 'giba',
  \     'active': {
  \         'left': [['mode', 'paste' ], ['readonly', 'filename', 'modified']],
  \         'right': [['lineinfo'], ['percent'], ['fileformat', 'fileencoding']]
  \     }
  \ }

" Hilight cursor line
set cursorline
highlight CursorLine ctermbg=232 cterm=bold

" Dim line numbers
highlight LineNr ctermfg=233

" Fzf shortcuts
map ; :Files<CR>
map <C-P> :Files<CR>

" NERDTree shortcut/settings
map <C-o> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let NERDTreeShowHidden=1

" Alt+leftarrow will go one window left, etc.
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

